### ISSUE TITLE
Impossible to center step card when using TourMatMenuModule

### ISSUE THREAD

**Issue by hakimio** [isaacplmann/ngx-tour#126]
Since all the steps must have an anchor point, there doesn't seem to be a way to center tour step card in the middle of the screen.

**Comment by isaacplmann** [comment]
That's true.

**Comment by hakimio** [comment]
Imho, it's rather important to have an option to skip the anchor point and just center the step card.

**Comment by isaacplmann** [comment]
I'll gladly review a PR.

**Comment by hakimio** [comment]
I could try to take a look at this issue if active item highlighting issue is solved.

**Comment by hakimio** [comment]
I've looked into this one and it's actually more complicated than I thought. Angular Material project positions its menu using cdk overlay (see [_setPosition](https://github.com/angular/material2/blob/master/src/lib/menu/menu-trigger.ts#L390) function) which we can not access because it's a private field. Manually setting CSS styling to reposition the menu as a dirty workaround causes loss of animations and possibly other issues.

Anyway, I found a simple workaround which is ok for now: create an extra invisible "div" with fixed position and attach the first step to it:
```css
.centered-tour-element {
    position: fixed;
    left: 50%;
    top: 50%;
    /* minus half of step element's width and height */
    transform: translate(-140px, -86px);
}
```
