### ISSUE TITLE
"prevBtnTitle" and "nextBtnTitle" configs have no effect when using MdMenu module

### ISSUE THREAD

**Issue by hakimio** [isaacplmann/ngx-tour#135]
Documentation states that "prevBtnTitle" and "nextBtnTitle" configs can be used to customize button texts but in reality they have absolutely no effect when "MdMenu" module is used. I would expect the configs to be used for button [tooltips](https://material.angular.io/components/tooltip/overview) (preferred behavior) or the documentation should state that those configs can not be used in "MdMenu" module.

**Comment by hakimio** [comment]
Another option would be to actually have text next t icon if people put any custom text.

Recently we made some user testing and found out that on mobile a lot of people were accidentally pressing "End" instead of the "next" arrow button because it's so small.

**Comment by hakimio** [comment]
@isaacplmann Yeah, the custom template would be a good solution for me, but I still think it's strange to have configs which don't actually do anything. Any reason you don't want to have tooltips in the default template?

**Comment by isaacplmann** [comment]
How about you paste your custom template code in this issue, that way if people find this issue and like the style you chose, they can just copy what you used.

**Comment by hakimio** [comment]
Sure.

Template:
```html
<mat-card (click)="$event.stopPropagation()">
  <mat-card-title>
    <span class="title-text">{{step?.title}}</span>
    <i class="material-icons title-close" (click)="tourService.end()">close</i>
  </mat-card-title>
  <mat-card-content>
    {{step?.content}}
  </mat-card-content>
  <mat-card-actions align="end">
    <button
        mat-button
        class="prev-button"
        [disabled]="!tourService.hasPrev(step)"
        (click)="tourService.prev()"
    >
      <i class="material-icons">chevron_left</i> {{step?.prevBtnTitle}}
    </button>
    <div class="divider"></div>
    <button
        mat-button
        class="next-button"
        [hidden]="!tourService.hasNext(step)"
        (click)="tourService.next()"
    >
      {{step?.nextBtnTitle}} <i class="material-icons">chevron_right</i>
    </button>
    <button
        mat-button
        (click)="tourService.end()"
        [hidden]="tourService.hasNext(step)"
    >
      {{step?.endBtnTitle}}
    </button>
  </mat-card-actions>
</mat-card>
```

CSS:
```css
.divider {
    flex: 1;
}

.title-close {
    cursor: pointer;
    position: absolute;
    right: 20px;
    top: 24px;
}

button.prev-button {
    padding-left: 6px;
}

button.next-button {
    padding-right: 6px;
}

mat-card-title {
    margin-right: 16px;
}

mat-card-title .title-text {
    line-height: 24px;
    font-size: 22px;
}

button[hidden] {
    display: none;
}
```
