### ISSUE TITLE
floating step

### ISSUE THREAD

**Issue by jkon** [isaacplmann/ngx-tour#183]
Is there a way to have a step that floats in the middle of the page, not attached any specific element? I want to have a step at the beginning that just floats in the center of the page, with the backdrop before the steps that go through all the elements on the page. Is this already possible, or would a change be needed?

**Comment by hakimio** [comment]
You can use a zero width and height centered div to achieve this:
```html
<div class="centered-tour-element" tourAnchor="start-tour"></div>
```
```css
.centered-tour-element {
    position: fixed;
    left: 50%;
    top: 50%;
    /* TODO: following should be half of your step component's width and height */
    transform: translate(-140px, -78px);
}
```
